import type { VibeId } from './types';

export const VIBE_LABELS: Record<VibeId, string> = {
  dark: 'Dark',
  floating: 'Floating',
  tense: 'Tense',
  repetitive: 'Repetitive',
  underground: 'Underground',
  wide: 'Wide',
  hypnotic: 'Hypnotic',
  metallic: 'Metallic',
  warm: 'Warm',
  deep: 'Deep',
  rolling: 'Rolling',
  cavernous: 'Cavernous',
  dry: 'Dry',
  unstable: 'Unstable',
  groovy: 'Groovy',
  nostalgic: 'Nostalgic',
  retrowave: 'Retrowave',
  gritty: 'Gritty',
  euphoric: 'Euphoric',
  cinematic: 'Cinematic',
  lucid: 'Lucid',
  void: 'Void',
  corroded: 'Corroded',
  static: 'Static',
  raw: 'Raw',
};
